#' Prepare and render the HML5 report
#'
#' This script generates the HTML5 report based on an enriched
#' `KOMODO2`-type list output by `run_KOMODO2()`.
#'
#' @param defs an enriched `KOMODO2`-type list generated by `run_KOMODO2()`
#' @param render.report logical: should the HTML5 report be generated (for
#' internal use only)
#'
#' @return A (possibly updated) `KOMODO2`-type list.
#'
#' @export

make_report <- function(defs, render.report = TRUE){

  # ================== Sanity checks ==================
  assertthat::assert_that(is.logical(render.report),
                          length(render.report) == 1,
                          all(c("KOMODO2", "list") %in% class(defs)))

  if(render.report){
    defs <- switch(tolower(defs$type),
                   significance = make_significance_report(defs),
                   correlation  = make_correlation_report(defs))

    # Open in browser
  if ( getOption("browser") != ""){ 
    utils::browseURL(gsub("//", "/", paste0(normalizePath(defs$output.dir),
                                            "/index.html"),
                          fixed = TRUE))
  }
  
  }

  invisible(defs)
}
